### PR TITLE
Refactor to use promise for htmlwidget's stored view

### PR DESCRIPTION
**Pull request by AliciaSchep**
See discussion at https://github.com/vegawidget/vegawidget/issues/38

A proposed refactoring of the internals of the htmlwidget to take advantage of promises.  I think this makes the code for adding listeners a lot cleaner, but also probably don't know enough about promises to fully understand the implications... @sa-lee and @ijlyttle let me know what you think!

### CODE REVIEW

**Comment by ijlyttle** [comment]
Hi @AliciaSchep, I know less about promises than you do, but I think this looks great! Indeed, it seems much cleaner. Like you, I am interested to hear @sa-lee's thoughts.

This is a more bookkeeping question for you - this PR is into the `shiny-interaction` branch, I'd like to take advantage of the non-shiny promise stuff in `master`. If you think the `shiny-interaction` branch is ready, I can make two merges. Otherwise, is there a way to split the PR to send the first bit to `master`?

If I need to, I can make the changes myself to `to-image.R` and to the `factory` and `getView` function in the JS code. (But I would not want to appear to be the author :))

Thanks so much!

**Comment by sa-lee** [comment]
I don't think this will break anything I've changed (in fact it should actually improve things for me too). I'm not ready to merge my changes so feel free to go ahead and merge this PR and I'll refactor my stuff accordingly.

**Comment by sa-lee** [comment]
Just a quick question about the code here (still learning JS)  but why initialize the view as a null scoped at the top level of the factory? Why not just create a promise at the top or inside a function in the factory then render just runs the promise as a side effect? Then all the other functions in the factory use ```this.getView() ```

**Comment by AliciaSchep** [comment]
Good question @sa-lee :smile: I had a similar thought, but I wasn't quite sure how best to create the promise at the top level, so  I left the initialization as is.  Do you have a code example for what you mean?  I'll take a stab myself, but if you already know how this would work in practice/code, please share!

**Comment by AliciaSchep** [comment]
@sa-lee I tried to do something along the lines of what (I think) you suggest but didn't get to something that worked. Perhaps @ijlyttle we can merge this change into this branch, and then if @sa-lee wants to do further refactor that can be a fresh PR?  

Re question of merging into master @ijlyttle , it seems like a bit more iteration may be warranted but I will leave that up to you.... I have no objections if you want to isolate the changes relevant to master branch and make that change yourself...

**Comment by sa-lee** [comment]
No worries @AliciaSchep - what you've done looks great! - I'll have a go of refactoring in a fresh PR based off what you've done here.

**Comment by ijlyttle** [comment]
It sounds like we have a plan 🎉

I will merge this PR into the `shiny-interaction` branch, then I will make an independent modification of the bits that we can use right now in master. (giving credit where credit is due, of course).

This should give @AliciaSchep and @sa-lee the space they (you) might need to get things sorted on the shiny end. 

FWIW, this will give @haleyjeppson and me a chance to test-drive the non-shiny implementation with some demos we are working on.

Thanks!

**Comment by ijlyttle** [comment]
I should have looked at this more-closely, and I will make a fix to this branch. 

I re-write the htmlwidgets directory with each new build with the Vega-Lite libraries, so the procedure (and maybe I need to change this) is:

modify `/data-raw/templates/vegawidget.js`

render `/data-raw/infrastructure.Rmd`

**Pull request merged**
