### PR TITLE
Intercept when printing within knitr to non-html to screenshot using vegawidget's png function

### PR DESCRIPTION
**Pull request by AliciaSchep**
A proposed fix for issue mentioned in #44 of printing within knitr for non-html formats.  The output used is trying to match what is in knitr screenshot method: https://github.com/yihui/knitr/blob/dccdad769b67a23d9cf8b8414f844e2a6a74f21e/R/plot.R#L499

### CODE REVIEW

**Comment by ijlyttle** [comment]
This looks really cool, thanks! 

I experimented with your code to see if svg would work - and [it did](https://github.com/ijlyttle/test)! If it's ok with you, I'd like to see if I can incorporate this into your PR. 

I think we might be able to use an `option` here, maybe `vegawidget.fig.format` (?), which could take the value `"png"` or `"svg"`.

**Comment by AliciaSchep** [comment]
Awesome! I had not tried svg, but since that works too then making the format an options sounds great!  

Note -- I have not tested this out with other formats than markdown -- probably worth testing on 'pdf' output too

**Comment by ijlyttle** [comment]
Good point, thanks! 

I might be overthinking this, but perhaps the default for pdf, could be svg?

**Comment by ijlyttle** [comment]
merged into feature-branch rmd-intercept

**Pull request merged**
