### PR TITLE
Shiny interaction

### PR DESCRIPTION
**Pull request by ijlyttle**
Beginning the long-overdue task of reviewing and merging into master

### CODE REVIEW

**Comment by ijlyttle** [comment]
Hi @AliciaSchep (and all),

This has taken me far-too-long to get to, but thanks to my company's vacation policy, I have some time at the end-of-the-year (yay?). It looks like Vega-Lite 3 might not be imminent, so I'm eager to tackle this in the meantime.

I have got things mergeable, mostly sorting out things in `vegawidget.js` to converge on `vega_promise` and `getVegaPromise()`.

I plan to go through the functions, asking (hopefully not-too-annoying questions), and proposing tweaks in the interests of consistency - for which I will beg your patience in advance.

I'll make PR's to this PR where we can discuss things as they come up.

**Comment by ijlyttle** [comment]
As an aside, @AliciaSchep, the `callView` function is my new favorite thing 🙌

**Comment by AliciaSchep** [comment]
Great! Happy to discuss or review any major changes... and apologies for any formatting sloppiness!  Re `callView` one thing I haven't fully figured out is using it to call a function  with parameters that includes a JS callback, specifically in the context of making that call from within shiny using `vw_call_view`.  Seemed not to respect htmlwidgets::JS.  But maybe I am mis-remembering b/c it was a while ago that I stumbled upon that... just figured I'd mention it in case you either run into the same thing or have conversely not had any issues or figured something out...

**Comment by ijlyttle** [comment]
Do you have in mind, for example, `view.addSignalHandler()` (but could be any of the functions that take a handler)? 

I suspect that there needs to be something in the receiving code that takes the string and converts it into a JS function, something like `eval()` but [not `eval()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Do_not_ever_use_eval!). 

I am experimenting with the JS function `Function()`, but I still don't know what our responsibilities are for sanitizing callbacks, or even if there is a need. For instance, does Vega limit the scope of callbacks?

Sorry for answering your questions with more questions, and probably not a lot of useful information :/

**Comment by AliciaSchep** [comment]
Yes am thinking of things like `view.addSignalHandler()`.  Currently adding the event or signal listeners is done through `htmlwidgets::onRender` and has to be done in the `renderVegawidget` block within shiny.  If someone wanted to add a listener dynamically in shiny, that can't be done with current implementation (although also not sure if there are many use cases for that)

**Comment by ijlyttle** [comment]
Let me have a think on that...

**Comment by ijlyttle** [comment]
Question for @sa-lee and @AliciaSchep:

If I can get the shiny apps to work, should I consider this as an assurance that I have incorporated the essentials of your shiny-interaction work? I know it's a necessary condition; I guess I'd like to get some idea of how close this is to a sufficient condition.

I fear that until we get the ES6 issues sorted out, we might have to resort to manual testing...

For Alicia, I have the binding app (slider for the cylinders) - for Stuart, I have the gapminder and the montecarlo apps - am I missing anything?

Thanks,

Ian

**Comment by sa-lee** [comment]
yay glad this has all gone through! sorry I've been MIA - I've been away for the holidays. Looking forward to catching up on all the changes you and @AliciaSchep have made recently

**Pull request merged**
