### PR TITLE
Preliminary implementation of to_svg

### PR DESCRIPTION
**Pull request by AliciaSchep**
Preliminary PR showing an implementation of to_svg function (#18).

Note: built this off a branch that had a bunch of commits unrelated to this feature... have removed the unrelated changes but not commits...

### CODE REVIEW

**Comment by ijlyttle** [comment]
This look super, thanks! There seems to be a bunch of directions we can go with this, so I want to make sure I do the "right" thing.

I am happy to merge this right away, and I can work on the documentation, etc. I don't want to step on what you are doing, but nether do I want to impose on you to do more stuff when you have already "broken the dam open". Please let me know.

Could this approach be extended to `to_png()`, as well? 

This also brings up the issue of contributor vs. author. Suffice to say that, barring any objection, I will add you as a contributor and I keep the door open to "author" - which we can discuss offline if you like.

**Comment by AliciaSchep** [comment]
Yes I believe this approach can be extended to `to_png()` as well... I found the Altair source code helpful for this, and I think it shows what would need to be changed for the PNG:  https://github.com/altair-viz/altair/blob/97cf10e87675f63f0b77cbd642f6eb4a206d91f7/altair/utils/headless.py#L63

Feel free to merge and build off this!  Or to give suggestions for what to add before it can be merged, either way is fine by me.  

One thought is that it might be nice for these to_svg and to_png functions to be able to accept either a spec or a widget object, given that this implementation uses the widget object itself.  

Re contributor, that sounds good to me.

**Comment by ijlyttle** [comment]
Quick question - looking more closely at the code, if `to_png()` and `to_svg()` were to accept vegawidgets, we will not have control over the element id (I don't think). 

One way around this would be to adapt your JS function `getVegaView()` to take a CSS selector string as an argument, then it could just look for ".vegawidget". Would there be any problem that I make such a change?

**Comment by AliciaSchep** [comment]
Yes @ijlyttle  that sounds good re getVegaView accepting CSS selector!  It was set to accept just ID because that was the use case relevant for shiny interaction (where you would know the ID because it is what you named the output).  But for that application can do the appending the '#' in the call to the getVegaView.

(another alternative is that I think that either the widget object could be modified to force use of a particular id or maybe the id could be extracted from the widget; i vaguely remember having done something like that in past)

**Pull request merged**
