### PR TITLE
Update to vegalite 5

### PR DESCRIPTION
**Pull request by ijlyttle**
address #159

Hi @AliciaSchep! Here's what I had on my computer, but could not quite get to work (`vw_to_vega()` wasn't working, if I remember well). I'll take a look at what you've done in #161, and see if there's a complete solution between the two :)

### CODE REVIEW

**Comment by AliciaSchep** [comment]
Hi @ijlyttle that was the same roadblock I hit and didn't get a good way around!  I think the approach of reading in the vega and vega-lite js files in directly to avoid users having to install the npm packages ended up breaking... I suspect we may end up either having to go the route of users having to install the npm packages so as to use the scripts vega provides or using a headless browser approach?

**Comment by ijlyttle** [comment]
I think we're back in business, thanks to your V8 magic @AliciaSchep!

There's a few things I think I need to sort out:

- [ ] can we use V8 everywhere instead of node? (I suspect we run into the "fetch" problem)
- [ ] why did I think that we needed vega-util?
- [ ] do I need to update the `vega_embed()` function?
- [ ] update documentation, etc.

**Comment by ijlyttle** [comment]
Hi @AliciaSchep, @sa-lee, @earowang - 

For those of you getting ready for UseR!, I apologize for the timing... 

Can you let me know if you think it is a bad (or even a good) idea for the master branch to use Vega-Lite 5?

I know I need to update some documentation before making a CRAN release, but could it be useful for you to have something new and "stable" to develop against.

(I suspect I know what Alicia's answer is, but I'll ask all-the-same)

**Comment by ijlyttle** [comment]
Note that vega-embed seems to have [gained a couple of arguments since v6.12.2](https://github.com/vega/vega-embed/compare/v6.12.2...v6.18.2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) (used in current master branch).


See [README.md](https://github.com/vega/vega-embed/blob/v6.18.2/README.md) for:

- `bind`
- `viewClass`

**Comment by ijlyttle** [comment]
The only place I can see that we use `vaga-util` is in `inst/bin/compile_scpec.js`, which has been obseleted by @AliciaSchep's V8 solution. 

As such, I'm thinking to remove it.

**Comment by AliciaSchep** [comment]
Does the node approach still work for the conversion to svg?  Seems like you're also trying to replace with V8 there too?  If that'll work that'd be really amazing! I assumed it would be blocked due to the file download part but seems like you may have figured out a way around that? 

Re question about getting main branch up to v5, that sounds good to me, although a feature branch could also be an alternative too, whatever makes sense!

**Comment by ijlyttle** [comment]
I *think* I may have found a way to to get the file-download part working - I have a JS function I that does what (I think) it needs to; the next step is to see if it *actually* works for converting to svg.

I like the idea of a feature branch for an alternative. I need to see how Altair plays with the new Vega-Lite version...

FWIW, Python Altair remains at an earlier Vega-Lite as some of the VL development broke some of Altair's assumptions. There do seem to be discussions on how to break the logjam, which is good to see.

**Pull request closed without merging**
