### PR TITLE
Vega-lite update

### LINKED ISSUE #128: `timeUnit` not working
When specifying `timeUnit` in the spec, the chart cannot be rendered. But the corresponding JSON spec works fine in the vega editor. The `timeUnit` section in the vignette also seems to show the issue https://vegawidget.github.io/vegawidget/articles/articles/dates-times.html#vega-lite-time-unit

```r
data <- jsonlite::fromJSON('[
      {"date": "Sun, 01 Jan 2012 00:00:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:01:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:02:00", "distance": 2},
      {"date": "Sun, 01 Jan 2012 00:03:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:04:00", "distance": 4},
      {"date": "Sun, 01 Jan 2012 00:05:00", "distance": 2},
      {"date": "Sun, 01 Jan 2012 00:06:00", "distance": 5},
      {"date": "Sun, 01 Jan 2012 00:07:00", "distance": 2},
      {"date": "Sun, 01 Jan 2012 00:08:00", "distance": 6},
      {"date": "Sun, 01 Jan 2012 00:09:00", "distance": 4},
      {"date": "Sun, 01 Jan 2012 00:10:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:11:00", "distance": 1},
      {"date": "Sun, 01 Jan 2012 00:12:00", "distance": 3},
      {"date": "Sun, 01 Jan 2012 00:13:00", "distance": 0},
      {"date": "Sun, 01 Jan 2012 00:14:00", "distance": 2},
      {"date": "Sun, 01 Jan 2012 00:15:00", "distance": 3}
    ]')

library(vegawidget)
list(
  `$schema` = vega_schema(), # specifies Vega-Lite
  data = list(values = data),
  mark = "bar",
  encoding = list(
    x = list(field = "date", timeUnit = list(unit = "minutes"), type = "temporal"),
    y = list(field = "distance", aggregate = "sum", type = "quantitative")
  )
) %>%
  as_vegaspec()
```

### PR DESCRIPTION
**Pull request by ijlyttle**
This is a long-overdue update of the Vega(-Lite) libraries, as well as a simplification of `vega_embed()`:

- Upgrade to Vega-Lite 4.17.0, Vega 5.17.0, vega-embed 6.12.2. 
- Removes the bulk of arguments  to `vega_embed()` in favor of `...`.

This process was so long, that VL had three releases since I started 😳

I see there is a problem with knit-printing, I need to see if the problem also appears with the "current" version. I imagine there is something new in RMarkdown/knitr... (edit: sorted out in #134)

@sa-lee, @earowang, @AliciaSchep could I impose on you to try out this version `install_github("vegawidget/vegawidget@vl-4.14.0")`? I want to make sure that this new version does not introduce difficulties for your vegawidget projects? I'll do the same for altair.

Thanks!

Note: fixes #128

### CODE REVIEW

**Comment by ijlyttle** [comment]
fixes #128

**Comment by ijlyttle** [comment]
altair (using Altair 4.1.0) check out (so far as I can tell) using Vega-Lite 4.1.17 and friends.

**Comment by AliciaSchep** [comment]
Making some small updates to support this schema update in vlbuildr, but I think the current version of package is mostly compatible with this update.  When will you plan to release to cran?

**Comment by ijlyttle** [comment]
@AliciaSchep I'm thinking maybe a week after the CRAN holiday ends, just to let the traffic die down - so maybe Jan. 11 or so. 

There's some documentation I could/should work on, so I can wait until you're sure you're ready.

**Comment by ijlyttle** [comment]
@AliciaSchep: I see you have some updates to vlbuildr that are waiting for this PR into be merged into master. 

I'll be happy to do merge this PR as soon as I get the signal from you that it's OK. (CRAN being a different question)

**Comment by AliciaSchep** [comment]
@ijlyttle No rush -- I mostly want to merge that PR sometime after you merge this one in, but before this change makes it to CRAN.  Feel free to merge this one whenever you're ready to!

**Comment by ijlyttle** [comment]
@AliciaSchep That sounds great! 

I'll circulate another "survey" soon to make sure we're all on board with CRAN submission.

**Pull request merged**
